version: "3"

services:
  nextjs-files:
    build:
      context: ../
      dockerfile: nextjs-docker/nextjs/Dockerfile
    image: signal-process-system-frontend-files
    container_name: nextjs-files
    restart: always
    networks:
      - frontend
      - mongo
    env_file:
      - ../.env.production
    volumes:
      - /mnt/iscsi_frontend/mount/files:/app/public/mount:rw

networks:
  frontend:
    exteral:
      name: mongo-replica-set_mongodb
