version: "3"

services:
  nextjs-files:
    build:
      context: ../
      dockerfile: nextjs-docker/nextjs/Dockerfile
    image: signal-process-system-frontend-files
    container_name: nextjs-files
    restart: always
    networks:
      - frontend
    env_file:
      - ../.env.production
    volumes:
      - /mnt/iscsi_frontend/mongodb/files:/app/public/mount:rw
    depends_on:
      - mongo

  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongo
    restart: always
    networks:
      - frontend
    ports:
      - 27017:27017
    volumes:
      - /mnt/iscsi_frontend/mongodb/db:/data/db:rw
      - /mnt/iscsi_frontend/mongodb/configdb:/data/configdb:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

      # docker run -e ME_CONFIG_MONGODB_SERVER=some-mongo -p 8081:8081 mongo-express

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - frontend
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: 1qaz2wsx
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

networks:
  frontend:
