version: "3"

services:
  nextjs-files:
    build:
      context: ../
      dockerfile: nextjs-docker/nextjs/Dockerfile
    image: signal-process-system-frontend-files
    container_name: nextjs-files
    restart: always
    env_file:
      - ../.env.production
    ports:
      - 3010:3000
    volumes:
      - /mnt/iscsi_frontend/mongodb/files:/app/public/mount:rw
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    # ports:
    #   - "27017:27017"
    volumes: -/mnt/iscsi_frontend/mongodb/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
