version: "3"

services:
  nextjs-files:
    build:
      context: ../
      dockerfile: nextjs-docker/nextjs/Dockerfile
    image: signal-process-system-frontend-files
    container_name: nextjs-files
    restart: always
    networks:
      - frontend
    ports:
      - 3010:3000
    env_file:
      - ../.env.production
    volumes:
      - /mnt/iscsi_frontend/mongodb/files:/app/public/mount:rw
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - frontend
    volumes:
      - /mnt/iscsi_frontend/mongodb/db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks:
  frontend:
